name: Dependabot

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write

jobs:
  renormalize:
    runs-on: ubuntu-slim
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - name: Run Git Renormalize
        run: git add --renormalize .
      - name: Check for changes
        id: git-check
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      - name: Commit and Push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git commit --amend --no-edit
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
